sudo: required
services:
    - docker

before_install:
    - docker build -t robified/cc_docker_react -f Dockerfile.dev .

script:
    - docker run -e CI=true robified/cc_docker_react npm run test

deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    app: 'docker-react'
    env: 'DockerReact-env'
    bucket_name: 'elasticbeanstalk-us-east-1-322331276199'
    bucket_path: 'docker-react'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: '$AWS_SECRET_KEY'
